#!/usr/bin/env bash
# Install 'Nginx' and configures the server to respond to requests with a string

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow "Nginx HTTP"
sudo chown -R "$USER:$USER" /var/www/html/index.nginx-debian.html
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
