#!/usr/bin/env bash
# Configures Nginx server so that '/redirect_me' is redirecting to another page

# Nginx configuration
SERVER_CONFIG=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;

	root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
	add_header X-Served-By \$hostname;
        location / {
                try_files \$uri \$uri/ =404;
        }

        error_page 404 /404.html;
        location = /404.html {
                internal;
        }

        if (\$request_filename ~ redirect_me) {
                rewrite ^ https://www.google.com permanent;
        }
}"

# Install Nginx
sudo apt-get update -y > /dev/null 2>&1
sudo apt-get install nginx -y > /dev/null 2>&1

# Activate Nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www

echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null 2>&1
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null 2>&1
echo "$SERVER_CONFIG" | sudo tee /etc/nginx/sites-available/default > /dev/null 2>&1
echo "$SERVER_CONFIG" | sudo tee /etc/nginx/sites-enabled/default > /dev/null 2>&1

if [ "$(sudo pgrep -c nginx)" -le 0 ];
then
        sudo service nginx start;
else
        sudo service nginx restart;
fi
