#!/usr/bin/env bash
# Install and configure HAproxy load balancer

DEFAULT_FILE="/etc/default/haproxy"
CFG_FILE="/etc/haproxy/haproxy.cfg"
DOMAIN="amrosati.tech"
LB_CFG=\
"

#--$DOMAIN-params-begin--

backend $DOMAIN-backend
        balance roundrobin
        server 118437-web-01 34.224.4.6:80 check
        server 118437-web-02 18.208.120.244:80 check

frontend $DOMAIN-frontend
        bind *:80
        mode http
        default_backend $DOMAIN-backend

#--$DOMAIN-params-end--
"


# Update and Install
sudo apt-get -y update > /dev/null 2>&1
sudo apt-get -y install --no-install-recommends software-properties-common > /dev/null 2>&1
sudo add-apt-repository -y ppa:vbernat/haproxy > /dev/null 2>&1
sudo apt-get -y install haproxy=2.8.\* > /dev/null 2>&1


# Configure HAproxy and save a copy of origin
[ -f "$DEFAULT_FILE" ] || touch "$DEFAULT_FILE"
[ -f "$CFG_FILE" ] || touch "$CFG_FILE"

sudo cp -a "$CFG_FILE"{,.original_copy}
echo "$LB_CFG" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null 2>&1

if [ "$(cat $DEFAULT_FILE | grep -Eco '^ENABLED=[01]$')" -gt 0 ];
then
	sudo sed -i 's/^ENABLED=0$/ENABLED=1/' "$DEFAULT_FILE";
else
	echo "ENABLED=1" | sudo tee -a "$DEFAULT_FILE" > /dev/null 2>&1;
fi


# Restart/Start HAproxy service
if [ "$(sudo pgrep -c haproxy)" -le 0 ];
then
	sudo service haproxy start;
else
	sudo service haproxy restart;
fi
