#!/usr/bin/env bash
# Manages 'manage_my_process' process

function pstart() {
	./manage_my_process &
	sudo echo "$!" > var/run/my_process.pid
}
function pstop() {
	kill "$(sudo cat /var/run/my_process.pid)"
	sudo rm -f /var/run/my_process.pid
}

case "$1" in
	start)
		pstart
		echo "manage_my_process started"
		;;
	stop)
		pstop
		echo "manage_my_process stopped"
		;;
	restart)
		pstop
		pstart
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
