#!/usr/bin/env bash
# Manages 'manage_my_process' process

function pstart() {
	./manage_my_process &
	"$(echo "$!" | sudo tee var/run/my_process.pid)" > /dev/null
}
function pstop() {
	pkill -f ./manage_my_process
	sudo rm -f /var/run/my_process.pid
}

case "$1" in
	start)
		pstart
		echo "manage_my_process started"
		;;
	stop)
		pstop
		echo "manage_my_process stopped"
		;;
	restart)
		pstop
		pstart
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
