#!/usr/bin/env bash
# Configures nginx to be running as nginx user and changes the listening
sed -i "s/#\?user */user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
